### ISSUE TITLE
Little Bug ;) 

### ISSUE THREAD

**Issue by Matetv** [Rencikas/ren-businesses#2]
Another small mistake!

Now when you craft an item, you will randomly get 2 to 6 items or more of the item you want to craft! 
No errors in the console!

**Comment by Rencikas** [comment]
> Another small mistake!
> 
> Now when you craft an item, you will randomly get 2 to 6 items or more of the item you want to craft! No errors in the console!

Downlead the latest release someone had already pointed this out and I have fixed it, it was a problem with item reward because it was in a for loop so some times you would get above 1 reward item
