### ISSUE TITLE
I get a config error

### ISSUE THREAD

**Issue by Jostekk** [Rencikas/ren-businesses#4]
this is my whole config :
Config = {
    QBinventory = 'lj-inventory',--//the name of inventory you are using
    AlowCuts = true,--// if this is true this means that all businesses have to take a cut from a employee sale
    PayoutSplit = 40,--// the cut procentage what the business takes what the rest is left for the employee
    Debug = false,--//if true it will enable polyzone debug
    businesses = {
        --//Default preset business
        ['burgershot'] = {--//key name stands for the business job name
            Blip = {--//blip this is where it shows the business location on the map
                [1] = {
                    pos = vec3(-581.15, -1064.5, 22.35),--//blip location using vector3
                    label = "Burgershot", --//blip label you can see on the map
                    color = 1,--// blip color
                    scale = 0.8,--// blip scale
                    id = 106--//blip icon ID       
                }
            },

            Register = {--//register where workers can write bills and players can pay them
                [1] = {--this means you can add a second register and so on
                    pos = vec3(-1194.8657, -893.4211, 14.1674),--//location of the box zone
                    heading = 340,--//box zone heading
                    length = 0.5,--//box zone length
                    width = 0.5,--// box zone width
                    minZ = 21.34,--// box zone min height
                    maxZ = 22.74 --// box zone max height                  
                },
                [2] = {--this means you can add a second register and so on
                    pos = vec3(-1193.3776, -895.1368, 14.2023),--//location of the box zone
                    heading = 0,--//box zone heading
                    length = 0.5,--//box zone length
                    width = 0.5,--// box zone width
                    minZ = 21.34,--// box zone min height
                    maxZ = 22.74 --// box zone max height                  
                }
                [3] = {--this means you can add a second register and so on
                pos = vec3(-1196.049, -891.3801, 14.2023),--//location of the box zone
                heading = 0,--//box zone heading
                length = 0.5,--//box zone length
                width = 0.5,--// box zone width
                minZ = 21.34,--// box zone min height
                maxZ = 22.74 --// box zone max height                  
                }
            },

            Storages = {--//storages this where you can store youre items
                [1] = {--this means you can add a second storage and so on
                    pos = vec3(-1194.0098, -894.2845, 14.1113),--//location of the box zone
                    heading = 0,--//box zone heading
                    length = 1,--//box zone length
                    width = 1,--// box zone width
                    minZ = 21.34,--// box zone min height
                    maxZ = 22.74,--// box zone max height 
                    stash = {
                        label = 'Odpri pult',--//this is the label of the target for the stash
                        name = 'burgershot_pult1',--//this is a stash ID 
                        weight = 50000,--//this is stash weight
                        slots = 5,--//this is stash slots
                        job = false--// if job = false that means that this storage is public. If you want a private stash replace false with your job name like this: job = "uwu"          
                 }
                [2] = {--this means you can add a second storage and so on
                    pos = vec3(-1195.3229, -892.2323, 14.0216),--//location of the box zone
                    heading = 0,--//box zone heading
                    length = 1,--//box zone length
                    width = 1,--// box zone width
                    minZ = 21.34,--// box zone min height
                    maxZ = 22.74,--// box zone max height 
                    stash = {
                        label = 'Odpri pult',--//this is the label of the target for the stash
                        name = 'burgershot_pult2',--//this is a stash ID 
                        weight = 50000,--//this is stash weight
                        slots = 5,--//this is stash slots
                        job = false--// if job = false that means that this storage is public. If you want a private stash replace false with your job name like this: job = "uwu"          
                    }
                 },
                [3] = {--this means you can add a second storage and so on
                    pos = vec3(-1203.2471, -895.7289, 14.483),--//location of the box zone
                    heading = 0,--//box zone heading
                    length = 1,--//box zone length
                    width = 1,--// box zone width
                    minZ = 21.16,--// box zone min height
                    maxZ = 23.76,--// box zone max height 
                    stash = {
                        label = 'Open hladilink',--//this is the label of the target for the stash
                        name = 'burgershot_hladilnik1',--//this is a stash ID 
                        weight = 500000,--//this is stash weight
                        slots = 50,--//this is stash slots
                        job = 'burgershot'--// if job = false that means that this storage is public. If you want a private stash replace false with your job name like this: job = "uwu"          
                    }
                },
                [4] = {--this means you can add a second storage and so on
                    pos = vec3(-1204.942, -893.7721, 13.9348),--//location of the box zone
                    heading = 270,--//box zone heading
                    length = 1,--//box zone length
                    width = 3,--// box zone width
                    minZ = 21.34,--// box zone min height
                    maxZ = 23.54,--// box zone max height 
                    stash = {
                        label = 'Open skladisce',--//this is the label of the target for the stash
                        name = 'burgershot_skladisce1',--//this is a stash ID 
                        weight = 500000,--//this is stash weight
                        slots = 50,--//this is stash slots
                        job =  false--// if job = false that means that this storage is public. If you want a private stash replace false with your job name like this: job = "uwu"          
                    }
                }
            },
            Craft = {--//This is where workers can craft items
                [1] = {--this means you can add a second craft and so on
                    pos = vec3(-1199.1029, -898.1125, 13.9114),--//location of the box zone
                    heading = 0,--//box zone heading
                    length = 1,--//box zone length
                    width = 1,--// box zone width
                    minZ = 21.36,--// box zone min height
                    maxZ = 22.56,--// box zone max height
                    items = {--// all the items you can craft
                        {
                           
                            item = 'steak',--//this is the items spawn name
                            label = 'Meso: 1x',--//this is the items label name
                            requiredLabel = 'Surovo Meso',--//this displays on the menu what items are required to make this item
                            required = {--//required item list
                                ['burger-raw'] = 1,--// [item spawn name] = item count
                                
                            }
                        },
                        {
                          
                            item = 'shotnuggets', 
                            label = 'Nageci',
                            requiredLabel = 'Kurje meso: 1x',
                            required = {
                                ['chicken_strips_raw'] = 1,--// [item spawn name] = item count
                                
                            }
                        }     
                        {
                          
                            item = 'heartstopper', 
                            label = 'Heartstopperi',
                            requiredLabel = 'Meso: 1x, Kruh za bruger: x1, Salata: 1x, Krompir : 1x',
                            required = {
                                ['steak'] = 1,--// [item spawn name] = item count
                                ['burger_bun'] = 2,
                                ['salad'] = 3,
                                ['fries'] = 4,
                                
                            }
                        }     
                        {
                           
                            item = 'moneyshot', 
                            label = 'Moneyshot',
                            requiredLabel = 'Meso: 1x, Kruh za bruger: x1, Salata: 1x, Krompir : 1x',
                            required = {
                                ['steak'] = 1,--// [item spawn name] = item count
                                ['burger_bun'] = 2,
                                ['salad'] = 3,
                                ['fries'] = 4,
                                
                            }
                        }  
                        {
                          
                            item = 'bleeder', 
                            label = 'Bleeder',
                            requiredLabel = 'Meso: 1x, Kruh za bruger: x1, Salata: 1x, Krompir : 1x',
                            required = {
                                ['steak'] = 1,--// [item spawn name] = item count
                                ['burger_bun'] = 2,
                                ['salad'] = 3,
                                ['fries'] = 4,
                                
                            }
                        }   
                        {
                          
                            item = 'torpedo', 
                            label = 'Torpedo',
                            requiredLabel = 'Meso: 1x, Kruh za bruger: x1, Salata: 1x, Krompir : 1x',
                            required = {
                                ['steak'] = 1,--// [item spawn name] = item count
                                ['burger_bun'] = 2,
                                ['salad'] = 3,
                                ['fries'] = 4,
                                
                            }
                        }   
                        {
                          
                            item = 'rimjob', 
                            label = 'Rimjob',
                            requiredLabel = 'Meso: 1x, Kruh za bruger: x1, Salata: 1x, Krompir : 1x',
                            required = {
                                ['steak'] = 1,--// [item spawn name] = item count
                                ['burger_bun'] = 2,
                                ['salad'] = 3,
                                ['fries'] = 4,
                                
                            }
                        }   
                        {
                          
                            item = 'shotfries', 
                            label = 'Pomfri',
                            requiredLabel = 'Krompir',
                            required = {
                                ['fries'] = 1,--// [item spawn name] = item count
                                
                                
                            }
                        }   
                        {
                          
                            item = 'cheesewrap', 
                            label = 'Sirov zavitek',
                            requiredLabel = 'Wrap : 1x',
                            required = {
                                ['wrap'] = 1,--// [item spawn name] = item count
                                
                                
                            }
                        }   
                        {
                          
                            item = 'chickenwrap', 
                            label = 'Kurji zavitek',
                            requiredLabel = 'Wrap : 1x',
                            required = {
                                ['wrap'] = 1,--// [item spawn name] = item count
                                
                                
                            }
                        }   
                        
                        
                    }            
                }
            },

            Duty = {--//this is where your workers can change there duty
                [1] = {--this means you can add a second duty and so on
                    pos = vec3(-1190.7782, -896.6539, 14.1387),--//location of the box zone
                    heading = 0,--//box zone heading
                    length = 1,--//box zone length
                    width = 1,--// box zone width
                    minZ = 21.32,--// box zone min height
                    maxZ = 25.32--// box zone max height                
                }
            },
            
            Outfit = {--//this is where workers can change into their saved outfits
                [1] = {--//this means you can add a second and so on
                    pos = vec3(-1205.9567, -890.1954, 14.3421),--//location of the box zone
                    heading = 270,--//box zone heading
                    length = 1,--//box zone length
                    width = 2,--// box zone width
                    minZ = 21.34,--// box zone min height
                    maxZ = 23.94--// box zone max height              
                }
            },
            Store = {--//this is where workers can buy ingredients
                [1] = {--//this means you can add a second store and so on
                    pos = vec3(-1202.7578, -892.0012, 14.2379),--//location of the box zone
                    heading = 0,--//box zone heading
                    length = 1,--//box zone length
                    width = 2,--// box zone width
                    minZ = 21.36,--// box zone min height
                    maxZ = 23.56,--// box zone max height
                    label = "Sestavine",--//store label
                    slots = 30,--//How many slots can the store have
                    items = {--//store item list
                        {
                            name = "chicken_strips_raw",--//item spawn name
                            price = 0,--//item price
                            amount = 100,--//item amount
                            info = {},--//item metadata
                            type = "item",--//item type
                            slot = 1,--//item slot where it will be placed on the inventory
                            authorizedJobGrades = {0, 1, 2, 3}--//job grades that can buy this item
                        },
                        {
                            name = "burger_bun",--//item spawn name
                            price = 0,--//item price
                            amount = 10,--//item amount
                            info = {},--//item metadata
                            type = "item",--//item type
                            slot = 2,--//item slot where it will be placed on the inventory
                            authorizedJobGrades = {0, 1, 2, 3,}--//job grades that can buy this item
                        }        
                        {
                            name = "burger-raw",--//item spawn name
                            price = 0,--//item price
                            amount = 10,--//item amount
                            info = {},--//item metadata
                            type = "item",--//item type
                            slot = 3,--//item slot where it will be placed on the inventory
                            authorizedJobGrades = {0, 1, 2, 3,}--//job grades that can buy this item
                        }      
                        {
                            name = "veggie",--//item spawn name
                            price = 0,--//item price
                            amount = 10,--//item amount
                            info = {},--//item metadata
                            type = "item",--//item type
                            slot = 4,--//item slot where it will be placed on the inventory
                            authorizedJobGrades = {0, 1, 2, 3,}--//job grades that can buy this item
                        }      
                        {
                            name = "salad",--//item spawn name
                            price = 0,--//item price
                            amount = 10,--//item amount
                            info = {},--//item metadata
                            type = "item",--//item type
                            slot = 5,--//item slot where it will be placed on the inventory
                            authorizedJobGrades = {0, 1, 2, 3,}--//job grades that can buy this item
                        }            
                        {
                            name = "wrap",--//item spawn name
                            price = 0,--//item price
                            amount = 10,--//item amount
                            info = {},--//item metadata
                            type = "item",--//item type
                            slot = 6,--//item slot where it will be placed on the inventory
                            authorizedJobGrades = {0, 1, 2, 3,}--//job grades that can buy this item
                        }                        
                    }                      
                }
            }
        }
        --//end off default business
    }
  }
}

And this is the error i get :
[    c-scripting-core] Creating script environments for ren-businesses
[script:ren-businesse] Error parsing script @ren-businesses/config/config.lua in resource ren-businesses: @ren-businesses/config/config.lua:36: '}' expected (to close '{' at line 19) near '['
[    c-scripting-core] Failed to load script config/config.lua.
[ citizen-server-impl] Started resource ren-businesses

**Comment by Rencikas** [comment]
You need to add a comma on this line
![image](https://user-images.githubusercontent.com/85559163/208063699-bf87ffca-8c07-459f-8de5-8a45acc4388e.png)
